### PR TITLE
fixed #747: When exporting the dataDictionaries dictionary, add a Name field.

### LINKED ISSUE #747: Enum classes export without Name attribution
## Your Environment(您的使用环境)

* smart-doc version:3.0.2
* plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin):3.0.2
* build tool version(maven or gradle):maven
* jdk version:17

## Expected Behavior(您期望的结果)
```
public enum RebootTypeEnum {
    /**
     * 软重启
     */
    SOFT(0, "软重启"),
    /**
     * 硬重启
     */
    HARD(1, "硬重启"),
    ;
    private final int code;
    private final String message;
    RebootTypeEnum(int code, String message) {
        this.code = code;
        this.message = message;
    }
    public int getCode() {
        return code;
    }
    public String getMessage() {
        return message;
    }
}
```

smart-doc.json
```
 dataDictionaries:[
 {
      "title": "重启类型",
      "enumClassName": "xxx.RebootTypeEnum",
      "codeField": "code",
      "descField": "message"
    }
]
```

Name | Code | Type | Description
-- | -- | -- | --
SOFT | 0 | int32 | 软重启
HARD | 1 | int32 | 硬重启

the Name attribution is important for a Enum class. so it should output the name field.

## Current Behavior(当前结果)

Code | Type | Description
-- | -- | --
 0 | int32 | 软重启
 1 | int32 | 硬重启

in current version, the doc didn't export the name field.

## Steps to Reproduce (Bug产生步骤，请尽量提供用例代码)

1.
2.
3.
4.

### PR DESCRIPTION
**Pull request by baboy**
"Name", as a fundamental attribute of the enumeration, should be included in the display when exporting the dictionary content to HTML.

Name作为枚举的原始基本属性，字典导出html内容添加对枚举Name的显示

### CODE REVIEW

**Comment by shalousun** [comment]
@baboy When submitting a PR next time, please use English. This will not only facilitate the community in directly generating the release log but also assist with the international promotion efforts. You may utilize some GPT tools to aid in translation.

下次提pr时请用英文，一个是方便社区直接生成release log，另一个是方便社区做国际化推广。你可以使用一些GPT工具来辅助翻译

**Comment by baboy** [comment]
> @baboy When submitting a PR next time, please use English. This will not only facilitate the community in directly generating the release log but also assist with the international promotion efforts. You may utilize some GPT tools to aid in translation.
> 
> 下次提pr时请用英文，一个是方便社区直接生成release log，另一个是方便社区做国际化推广。你可以使用一些GPT工具来辅助翻译

Got it, the issue have been edit yet.

**Comment by shalousun** [comment]
@baboy The markdown template also needs updating

**Comment by baboy** [comment]
> @baboy The markdown template also needs updating

Done!

**Review by shalousun — APPROVED** [review]

**Pull request merged**
